// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3U-ToSHeMcu32oyGowBHx_NleB6gJQus',
    appId: '1:448243860576:web:031d9e6311ffbf20b9ef05',
    messagingSenderId: '448243860576',
    projectId: 'appointmentappfront',
    authDomain: 'appointmentappfront.firebaseapp.com',
    storageBucket: 'appointmentappfront.firebasestorage.app',
    measurementId: 'G-FK65XHQMNV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOnKBXQELSuEaxQK-kuBqJTj0Np-pM4kQ',
    appId: '1:448243860576:android:2f9c4df10064fbcbb9ef05',
    messagingSenderId: '448243860576',
    projectId: 'appointmentappfront',
    storageBucket: 'appointmentappfront.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3U-ToSHeMcu32oyGowBHx_NleB6gJQus',
    appId: '1:448243860576:web:c44852f113abe226b9ef05',
    messagingSenderId: '448243860576',
    projectId: 'appointmentappfront',
    authDomain: 'appointmentappfront.firebaseapp.com',
    storageBucket: 'appointmentappfront.firebasestorage.app',
    measurementId: 'G-EFD93G2KRF',
  );

}